name: CI

on: [pull_request]

jobs:
  linux:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        working-directory: rider-godot
        run: ./gradlew build